# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170820_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='post',
        ),
    ]
